language: elm
if: branch = main

install:
- if [[ "$GITHUB_TOKEN" != "" ]]; then git clone https://${GITHUB_TOKEN}@github.com/elmw/deploy "$HOME/deploy"; fi
- if [[ -d ~/deploy ]]; then bash "$HOME/deploy/install.sh"; fi

script:
- if [[ ! -d "$HOME/deploy" ]]; then elm-test; fi
- if [[ -d "$HOME/deploy" ]]; then bash "$HOME/deploy/script.sh"; fi
